stages:
    - build
    - quality
    - tests

include:
  - /pipelines/templates/quality-template.yml
  - /pipelines/templates/tests-template.yml

image: node:latest

cache: &global_cache
  key:
    files:
      - pnpm-lock.yaml
  paths:
    - .pnpm-store
    - node_modules/
  policy: pull

before_script:
    - curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm@7
    - pnpm config set store-dir .pnpm-store

build:
    stage: build
    cache:
        <<: *global_cache
        policy: pull-push
    script:
        - pnpm install
        - pnpm build
    artifacts:
        paths:
            - dist/*

static-typing-job:
  stage: quality

lint-job:
  stage: quality

run-tests:
  stage: tests
